## Known bugs/to be fixed:

* get_id functions throws error when reading records saved in lists in the Python interpreter. Probably affects the other record-independent functions
